### ISSUE TITLE
doesn't work in IE 11.0

### ISSUE THREAD

**Issue by cmayankc** [Sandglaz/bootstrap-tagautocomplete#14]
Doesn't work in IE 11.

The issue is that splitText method on text node element does not split the node.
Using splitDataNode can fix the issue though but it seems to be slowing down the selection.

**Comment by mscofield** [comment]
Replace this code:

this.node.splitText(this.index_for_split);
        this.node.nextSibling.splitText(this.length_of_query);
        this.node.nextSibling.nodeValue = this.updater(val);

With this:

var caretPosition = getCaretPosition(this.$element[0]);
        var text = $('#' + this.$element[0].id).text();
        
        text = text.substring(0, caretPosition) + val.substring(1, val.length) + ' '
        + text.substring(caretPosition, text.length);

        $('#' + this.$element[0].id).html(text);

**Comment by bhritchie** [comment]
I've rewritten the `select()` method to avoid the use of `splitText()`, using @mscofield 's suggestion as a starting point. This gives us IE compatibility.

**Comment by surajcgalande** [comment]
thank you very much for considering my suggestion.
